#!/bin/bash

if [ "$SLURM_NNODES" -eq 1 ]; then
  export NCCL_P2P_LEVEL=NVL
fi
export NCCL_IB_TC=96
export NCCL_IB_SL=1
export NCCL_IB_GID_INDEX=3
export NCCL_IB_TIMEOUT=22
export NCCL_IB_QPS_PER_CONNECTION=8
export NCCL_IB_SPLIT_DATA_ON_QPS=1
export NCCL_IB_ADAPTIVE_ROUTING=1
export NCCL_BUFFSIZE=16777216
export NCCL_NET_GDR_LEVEL=PIX
export NCCL_NET_GDR_READ=1
export NCCL_DEBUG=INFO

export DATASET_ENABLE_CACHE=1
export USE_HF=1

export OMP_NUM_THREADS=$(nproc)
export OMP_DYNAMIC=TRUE
